st = input().split()
s = int(st[0])
t = int(st[1])
ab = input().split()
a = int(ab[0])
b = int(ab[1])
mn = input().split()
m = int(mn[0])
n = int(mn[1])
apples = map(int, input().rstrip().split())
oranges = map(int, input().rstrip().split())

finalApples = sum(s <= a + d <= t for d in apples)
finalOranges = sum(s <= b + d <= t for d in oranges)
print(finalApples)
print(finalOranges)